### ISSUE TITLE
[申請人工文章判定] [中性評價] Comment from swerfg03joe

### ISSUE THREAD

**Issue by swerfg03joe** [1101-GS4719-C/Python-Community-GS4719-C#1010]
原文被AI評價為「中性評價」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/747#discussioncomment-4600068
原文內容：
雖然多數的語法都可以在這個網站中找到，但是過於冷僻的模組或是新的第三方模組還是得去其他地方找

說明：

**Comment by chia-kai-chang** [comment]
我認同此篇文章的AI判定結果
