### ISSUE TITLE
[申請人工文章判定] [資訊量不足] Discussion from BlahFish1006

### ISSUE THREAD

**Issue by BlahFish1006** [1101-GS4719-C/Python-Community-GS4719-C#1025]
原文被AI評價為「資訊量不足」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1022
原文內容：
本篇新聞在講一個花蓮慈濟醫院與台灣骨王生技公司合作共同研究，超越微創的脊椎手術！
透過AR擴增實境的技術，利用攝影機與影像分析來計算3度空間的位置，讓顯示器中顯示虛擬物件，並與真實世界進行實際互動，
讓醫師在手術中可達到用肉眼直觀顯示，隱藏在皮膚肌肉下的神經與血管，讓器械在小於1mm的誤差下，能精準的投射出真實的體內結構，降低脊椎手術時可能傷害周圍的神經與血管的風險。

🔆而目前該研究在手術術前計畫的合作結果，也已實際應用在臨床上，成功幫助0402台鐵太魯閣號出軌事件中，一名嚴重骨盆骨折傷者順利重建骨盆。

不久前跟朋友去逛了去年(2022)的台灣醫療科技展，發現近期有越來越多混合實境的技術被實際應用於臨床上，協助醫師進行手術、診治、甚至學習，不斷突破人們對醫病體驗中的想像，甚是令人興奮。

新聞來源：https://www.tcnews.com.tw/medicine/item/16679.html

說明：想請求指路是哪部分資訊量不足QQ

**Comment by chia-kai-chang** [comment]
建議可以多說說，「自己」對這篇文章，這個應用的看法

不用管政治正不正確，嘗試條理分明，清晰地說出自己的看法

也可以說說，你在看了這則新聞後，對未來的工作憧憬有無影響? 未來是否也想從事類似的研究。

你先試試看，我們再隨時Issue討論。

**Comment by BlahFish1006** [comment]
老師但我在貼文中已有包含自己的想法了，最後是我自己個人的經驗的說QQ

**Comment by chia-kai-chang** [comment]
我們加了一條規則，如果被教師或助教用Emoji😄標示，該貼文排除AI判斷結果
所以目前這篇文章 #1022  可以得到3點

**Comment by BlahFish1006** [comment]
了解~ 謝謝老師！
