### ISSUE TITLE
[申請人工文章判定] [中性評價] Comment from Tuoresa

### ISSUE THREAD

**Issue by Tuoresa** [1101-GS4719-C/Python-Community-GS4719-C#1032]
原文被AI評價為「中性評價」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/532#discussioncomment-4617763
原文內容：
感覺非常有趣！！好想試用看看！
有時候想聽音樂總是找很久還找不到符合當下感覺得歌曲
但也說不上來想聽什麼樣的歌

很期待真正使用到時的感受
或許能解決好想聽音樂卻總是頻率不對的問題哈哈

說明：
感覺我有提出實際舉例卻評斷中等，有些人只是一句敘述但他們有火箭欸。好好笑其實沒有關係，我只是想試試看這個github issue功能是怎麼運作的 好神奇

**Comment by chia-kai-chang** [comment]
AI會自動給 👀 或 👍 ，火箭 🚀 是人類添加的，只有老師或助教加上的火箭 🚀 才會加點數喔。計分規則最近有一點調整，可以參考這邊[1111Python計分規則](https://github.com/NCU-GS4719-Python/Python-Community/wiki/1111-%E3%80%8C%E7%A8%8B%E5%BC%8F%E8%A8%AD%E8%A8%88-Python%E3%80%8D%E8%A8%8E%E8%AB%96%E5%8D%80%E7%A9%8D%E5%88%86%E8%A8%88%E7%AE%97%E8%A6%8F%E5%89%87)。

你的回文寫得很用心喔，老師手動給你一個 👍
