### ISSUE TITLE
[申請人工文章判定] [資訊量充足] Comment from dabbie109303501

### ISSUE THREAD

**Issue by dabbie109303501** [1101-GS4719-C/Python-Community-GS4719-C#1056]
原文被AI評價為「資訊量充足」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/986#discussioncomment-4618351
原文內容：
我覺得AI歧視的問題有一部分也反映出目前存在的社會問題
當然在文章中提到的撞死老婦的行為無法原諒 需要給AI加上生死的觀念
但在AI歧視黑人和婦女的方面 我認為AI的判斷情有可原
因為AI是從統計資料中學習的 而在目前的社會中 又有多少男女同工不同酬和種族歧視的案例?
雖然與以前相比已經少很多 但仍有此現象 尤其因中國的covid19 讓近幾年的美國

說明：
無

**Comment by chia-kai-chang** [comment]
人工判定 🎉
