### ISSUE TITLE
[申請人工文章判定] [中性評價] Discussion from Tuoresa

### ISSUE THREAD

**Issue by Tuoresa** [1101-GS4719-C/Python-Community-GS4719-C#1076]
原文被AI評價為「中性評價」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1075
原文內容：
於2018年5月5日發射，同年11月成功降落於火星並開始執行任務的洞察號探測器
主要任務內容為藉由地震波的觀測資料，使科學家能夠建構火星內部的成份及組成。

2022年12月21日 NASA嘗試與電量極低的洞察號聯繫未果，於是宣布洞察號已電力耗盡並關機。

每次看見這種衛星或是星體探測儀與我們失去聯繫都有一種生命殞落的悲傷
（雖然它們說白了不過是

說明：想請問老師這篇文章的問題~

**Comment by chia-kai-chang** [comment]
因為這篇文章基本點數是3點，所以AI的要求比較嚴格一些
不過既然AI沒有標示為 👀 ，就表示你已取得3點了

寫得不錯很生動，但是我覺得3點 ok的

結案嚕~
