### ISSUE TITLE
[申請人工文章判定]%20[資訊量充足]%20Discussion%20from%20shuxian12

### ISSUE THREAD

**Issue by shuxian12** [1101-GS4719-C/Python-Community-GS4719-C#1159]
原文被AI評價為「資訊量充足」%0A原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1158%0A原文內容：%0A大家好，我是資電院學士班大三的陳紓嫻，因為前幾天有篇%20%231153%20有關chatGPT是否會取代工程師的討論，因此我今天想來和介紹一下ChatGPT的前身和一些訓練的方式。%0D%0A%0D%0A%23%23%23%20**ChatGPT簡介**%0D%0AＣhatGPT%20是由OpenAI在去年底推出的AI對話機器人，而大家從官網上都可以發現他的訓練過程與InstructGPT%20非常類似，連訓練流程%0A%0A說明：%0A

**Comment by chia-kai-chang** [comment]
我認同AI的判斷，同時幫你加贈了點數 🎉。不過如果你能再補充一下參考資料來源，會更完整。
