### ISSUE TITLE
[申請人工文章判定] [資訊量充足] Comment from JohnnyXiao1024

### ISSUE THREAD

**Issue by JohnnyXiao1024** [1101-GS4719-C/Python-Community-GS4719-C#1177]
原文被AI評價為「資訊量充足」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1156#discussioncomment-5371751
原文內容：
感謝同學分享AI算圖的主題
近年隨著AI繪圖的興起，利用精準的題詞產生優秀的畫作已然成為一們新顯學
分享兩個好用的網站給大家：[Prompt Hero]（https://prompthero.com/） 和 [clip interrogator]

說明：

**Comment by chia-kai-chang** [comment]
@JohnnyXiao1024 同學的AI應用相當多元。而且分享時，有文章，有連結，有圖片。內容相當豐富。加贈 🎉
