### ISSUE TITLE
[申請人工文章判定] [資訊量充足] Comment from curtis1017

### ISSUE THREAD

**Issue by curtis1017** [1101-GS4719-C/Python-Community-GS4719-C#1189]
原文被AI評價為「資訊量充足」
原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1180#discussioncomment-5473830
原文內容：
這讓我想到當我們在使用Colab的時候。我們有時候會因為撰寫程式時寫到有點興致缺缺，所以我發現了一個功能，那就是Colab上面可以跑出柴犬及貓的動態圖像，會在上面跑來跑去。開啟的方法是：開啟Colab，然後點選設定，再來點左方的其他，最後把柯基犬模式和貓咪模式打開後，最後就大功完成囉！

說明：

**Comment by chia-kai-chang** [comment]
我同意AI的判斷
