### ISSUE TITLE
[申請人工文章判定]%20[資訊量充足]%20Discussion%20from%20Chienyuuu6

### ISSUE THREAD

**Issue by Chienyuuu6** [1101-GS4719-C/Python-Community-GS4719-C#1281]
原文被AI評價為「資訊量充足」%0A原文網址：https://github.com/NCU-GS4719-Python/Python-Community/discussions/1280%0A原文內容：%0A今天早上買咖啡的路上突然想到：系際盃快到了，可是我們人手超不足，根本沒辦法進行場下的數據統計。%0A%0A我突然想到如果可以訓練AI閱讀一場籃球賽，肯定很猛！會讓一個球隊的運作更有效率，但我覺得困難度蠻高的，因為籃球場上的變化很多，簡單的數據分類就有得分、籃板、抄截、助攻、阻攻、失誤等等的，假設能夠判斷並記錄每個球員的攻守數據真的很強～%0A%0A如果真的能夠實現的話，我更%0A%0A說明：%0A

**Comment by chia-kai-chang** [comment]
這是個很有趣的議題。我的AI專題也有做一些運動科技的探討，歡迎同學來選修。
